# Generated by Django 4.2.4 on 2023-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_customuser_bio_customuser_dob_tabledata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='date',
            field=models.DateField(),
        ),
    ]
