# Generated by Django 4.2.4 on 2023-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_remove_group_bio_group_groupbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupbio',
            field=models.TextField(default=''),
        ),
    ]
