# Generated by Django 4.2.4 on 2023-09-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_statdata'),
        ('gym_app', '0011_alter_customuser_current_group'),
    ]

    operations = [
    ]
