# Generated by Django 4.2.4 on 2024-07-06 01:52

from django.db import migrations, models
import gym_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0013_customuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=gym_app.models.user_directory_path),
        ),
    ]
