# Generated by Django 4.2.4 on 2024-07-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0014_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMetadata',
        ),
    ]
